import type { Aircraft, Platform } from "./gameModel";

export const PLATFORMS: Platform[] = [
  {
    id: "fleet-aviation-ship",
    name: "Fleet aviation ship",
    short: "FLEET AVIATION SHIP",
    role: "Task-group command · long-range aviation",
    points: 30,
    crew: 2110,
    aviationCapacity: 62,
    aviationKinds: ["catapult", "short-deck", "rotary", "uncrewed-fixed-wing", "uncrewed-vertical"],
    armamentSlots: 2,
    armamentIds: [],
    capabilities: ["coordinates long-range fixed-wing and rotary sorties", "sustains airborne surveillance and task-group command", "supports assisted-launch, short-deck, rotary, and uncrewed aircraft"],
    screenUnit: false,
    airDefenseValue: 0,
    aswValue: 0,
    warfare: ["reconnaissance"],
    note: "Fictional full-deck category supporting several launch methods; all capacity and personnel values are invented.",
  },
  {
    id: "short-deck-aviation-ship",
    name: "Short-deck aviation ship",
    short: "SHORT-DECK AVIATION",
    role: "Short take-off aviation · task-group command",
    points: 24,
    crew: 1280,
    aviationCapacity: 44,
    aviationKinds: ["short-deck", "rotary", "uncrewed-fixed-wing", "uncrewed-vertical"],
    armamentSlots: 2,
    armamentIds: [],
    capabilities: ["launches short-takeoff combat aircraft without assisted launch", "coordinates rotary and uncrewed aviation", "provides a smaller mobile aviation command node"],
    screenUnit: false,
    airDefenseValue: 0,
    aswValue: 0,
    warfare: ["reconnaissance"],
    note: "Fictional ramp-deck category emphasizing short take-off aircraft, rotorcraft, and uncrewed aviation.",
  },
  {
    id: "expeditionary-aviation-dock",
    name: "Expeditionary aviation dock",
    short: "EXPEDITIONARY DOCK",
    role: "Rotorcraft · landing craft · relief command",
    points: 18,
    crew: 740,
    aviationCapacity: 32,
    aviationKinds: ["rotary", "uncrewed-vertical"],
    armamentSlots: 2,
    armamentIds: ["maritime-safeguarding-pack"],
    capabilities: ["moves relief teams and landing craft", "supports rescue, lift, and vertical replenishment", "commands a temporary littoral support area"],
    screenUnit: false,
    airDefenseValue: 0,
    aswValue: 0,
    warfare: ["surface-operations", "reconnaissance", "maritime-interdiction"],
    note: "Fictional multi-purpose aviation and well-deck category for expeditionary support and disaster response.",
  },
  {
    id: "uncrewed-aviation-ship",
    name: "Low-signature uncrewed aviation ship",
    short: "LOW-SIGNATURE UNCREWED SHIP",
    role: "Persistent uncrewed air operations · reduced-signature command",
    points: 15,
    crew: 420,
    aviationCapacity: 40,
    aviationKinds: ["uncrewed-fixed-wing", "uncrewed-vertical"],
    armamentSlots: 2,
    armamentIds: [],
    capabilities: ["sustains persistent uncrewed sorties", "reduces visual and electronic cues while aircraft are recovered", "relays distributed sensor data while limiting crewed exposure"],
    screenUnit: false,
    airDefenseValue: 0,
    aswValue: 0,
    warfare: ["reconnaissance"],
    note: "Fictional reduced-signature vessel designed around uncrewed aircraft rather than a particular procurement programme.",
    visualSignature: "low",
  },
  {
    id: "area-defense-destroyer",
    name: "Area-defence destroyer",
    short: "AREA-DEFENCE DESTROYER",
    role: "Air and missile defence coordination",
    points: 14,
    crew: 294,
    aviationCapacity: 4,
    aviationKinds: ["rotary", "uncrewed-vertical"],
    armamentSlots: 4,
    armamentIds: ["area-air-interceptor-pack", "missile-defense-interceptor-pack", "surface-guided-effect-pack", "surface-land-effect-pack", "shipborne-asw-pack"],
    capabilities: ["coordinates a wide-area air picture", "provides the strongest missile-defence host in the model", "supports one compact rotary or uncrewed detachment"],
    screenUnit: true,
    airDefenseValue: 2,
    aswValue: 1,
    warfare: ["air-defense", "reconnaissance"],
    note: "Fictional ocean-going air-defence category with abstracted sensors, interceptors, and aviation support.",
  },
  {
    id: "multirole-frigate",
    name: "Multi-role frigate",
    short: "MULTI-ROLE FRIGATE",
    role: "Escort · anti-submarine search · sea control",
    points: 10,
    crew: 188,
    aviationCapacity: 5,
    aviationKinds: ["rotary", "uncrewed-vertical"],
    armamentSlots: 3,
    armamentIds: ["area-air-interceptor-pack", "surface-guided-effect-pack", "surface-land-effect-pack", "shipborne-asw-pack", "maritime-safeguarding-pack"],
    capabilities: ["screens a high-value unit", "tows and processes an undersea search array", "supports a maritime helicopter plus a compact uncrewed detachment"],
    screenUnit: true,
    airDefenseValue: 1,
    aswValue: 2,
    warfare: ["air-defense", "undersea-operations", "reconnaissance", "maritime-interdiction"],
    note: "Fictional balanced escort category able to pair a maritime helicopter with vertical-flight drones.",
  },
  {
    id: "stealth-littoral-corvette",
    name: "Stealth littoral corvette",
    short: "STEALTH LITTORAL CORVETTE",
    role: "Coastal manoeuvre · signature control · patrol",
    points: 6.5,
    crew: 78,
    aviationCapacity: 4,
    aviationKinds: ["rotary", "uncrewed-vertical"],
    armamentSlots: 2,
    armamentIds: ["surface-guided-effect-pack", "shipborne-asw-pack", "mine-neutralization-pack", "maritime-safeguarding-pack"],
    capabilities: ["patrols confined and shallow water", "uses reduced signatures for coastal reconnaissance", "hosts a compact vertical-flight or remote-systems detachment"],
    screenUnit: true,
    airDefenseValue: 0,
    aswValue: 1,
    warfare: ["surface-operations", "reconnaissance", "maritime-interdiction"],
    note: "Fictional shallow-water combatant emphasizing reduced signatures, manoeuvrability, and multi-mission work.",
    visualSignature: "low",
  },
  {
    id: "autonomous-mine-support-ship",
    name: "Autonomous mine-support ship",
    short: "AUTONOMOUS MINE SUPPORT",
    role: "Mine clearance · remote-systems command",
    points: 7,
    crew: 58,
    aviationCapacity: 10,
    aviationKinds: ["rotary", "uncrewed-vertical"],
    armamentSlots: 4,
    armamentIds: ["mine-neutralization-pack", "maritime-safeguarding-pack"],
    capabilities: ["commands remote mine-search vehicles", "marks and verifies a temporary cleared lane", "supports airborne, surface, and underwater inspection systems"],
    screenUnit: true,
    airDefenseValue: 0,
    aswValue: 1,
    warfare: ["mine-countermeasures", "reconnaissance", "maritime-interdiction"],
    note: "Fictional host ship for autonomous surface, airborne, and underwater mine-search systems.",
  },
  {
    id: "air-independent-submarine",
    name: "Air-independent patrol submarine",
    short: "AIR-INDEPENDENT SUBMARINE",
    role: "Quiet patrol · confined-water denial",
    points: 9.5,
    crew: 46,
    aviationCapacity: 0,
    aviationKinds: [],
    armamentSlots: 2,
    armamentIds: ["submarine-heavy-effect-pack"],
    capabilities: ["conducts quiet patrols in confined water", "tracks surface and undersea contacts covertly", "lays a temporary observation or denial barrier"],
    screenUnit: false,
    airDefenseValue: 0,
    aswValue: 2,
    warfare: ["undersea-operations", "reconnaissance"],
    note: "Fictional conventionally powered category using an abstracted air-independent endurance advantage.",
    visualSignature: "low",
  },
  {
    id: "long-endurance-submarine",
    name: "Long-endurance attack submarine",
    short: "LONG-ENDURANCE SUBMARINE",
    role: "Ocean patrol · sea denial · reconnaissance",
    points: 13,
    crew: 96,
    aviationCapacity: 0,
    aviationKinds: [],
    armamentSlots: 3,
    armamentIds: ["submarine-heavy-effect-pack", "submarine-land-effect-pack"],
    capabilities: ["sustains an ocean patrol beyond the surface screen", "collects covert reconnaissance", "supports sea denial or a bounded land effect when paired with the relevant package"],
    screenUnit: false,
    airDefenseValue: 0,
    aswValue: 3,
    warfare: ["undersea-operations", "reconnaissance"],
    note: "Fictional ocean-going undersea category; propulsion, sensors, weapons, and endurance are deliberately unspecified.",
    visualSignature: "low",
  },
  {
    id: "undersea-systems-tender",
    name: "Undersea systems tender",
    short: "UNDERSEA SYSTEMS TENDER",
    role: "Autonomous undersea deployment · analysis",
    points: 8,
    crew: 68,
    aviationCapacity: 8,
    aviationKinds: ["uncrewed-vertical", "rotary"],
    armamentSlots: 4,
    armamentIds: ["shipborne-asw-pack", "mine-neutralization-pack"],
    capabilities: ["deploys large uncrewed underwater vehicles", "analyzes distributed acoustic data", "supports repeated inspection or neutralization runs"],
    screenUnit: false,
    airDefenseValue: 0,
    aswValue: 2,
    warfare: ["undersea-operations", "mine-countermeasures", "reconnaissance"],
    note: "Fictional support vessel for large uncrewed undersea vehicles and distributed sensing teams.",
  },
];

export const AIRCRAFT: Aircraft[] = [
  { id: "deck-multirole-aircraft", name: "Deck-launched multirole aircraft", short: "DECK MULTIROLE AIRCRAFT", role: "Escort · identification · configurable strike", points: 1.1, aircrew: 1, supportCrew: 8, kind: "catapult", armamentSlots: 1, armamentIds: ["air-to-air-mission-pack", "airborne-extended-interceptor-pack", "airborne-anti-surface-pack", "airborne-land-effect-pack", "airborne-decoy-pack"], capabilities: ["launches with assisted fixed-wing equipment", "conducts long-range identification and escort", "accepts one air, surface, land, or protection mission pack"], warfare: ["reconnaissance"], missionReach: "420 invented nautical miles", trackCapacity: 8, trackingMethods: ["active radar", "infrared", "cooperative network"] },
  { id: "deck-long-range-strike-aircraft", name: "Assisted-launch long-range strike aircraft", short: "LONG-RANGE DECK STRIKE", role: "Distant maritime effect · deep land effect", points: 1.45, aircrew: 2, supportCrew: 11, kind: "catapult", armamentSlots: 2, armamentIds: ["airborne-anti-surface-pack", "airborne-land-effect-pack", "airborne-emitter-homing-pack", "airborne-decoy-pack"], capabilities: ["carries two compatible mission packs on a distant strike sortie", "correlates passive and cooperative tracks before release", "requires an assisted-launch aviation ship"], warfare: ["reconnaissance"], missionReach: "540 invented nautical miles", trackCapacity: 6, trackingMethods: ["passive emitter", "cooperative network", "scene correlation"] },
  { id: "deck-interceptor-aircraft", name: "Assisted-launch fleet interceptor", short: "FLEET INTERCEPTOR", role: "Outer air defence · guided-threat intercept", points: 1.25, aircrew: 1, supportCrew: 9, kind: "catapult", armamentSlots: 1, armamentIds: ["air-to-air-mission-pack", "airborne-extended-interceptor-pack", "airborne-decoy-pack"], capabilities: ["holds a distant combat-air patrol", "accepts a local or extended interceptor pack", "shares cooperative tracks with a selected air-defence host"], warfare: ["reconnaissance"], missionReach: "470 invented nautical miles", trackCapacity: 10, trackingMethods: ["active radar", "infrared", "cooperative network"] },
  { id: "short-takeoff-aircraft", name: "Short-takeoff multirole aircraft", short: "SHORT-TAKEOFF MULTIROLE", role: "Compact-deck intercept · configurable strike", points: 1.2, aircrew: 1, supportCrew: 9, kind: "short-deck", armamentSlots: 1, armamentIds: ["air-to-air-mission-pack", "airborne-extended-interceptor-pack", "airborne-anti-surface-pack", "airborne-land-effect-pack", "airborne-decoy-pack"], capabilities: ["launches from a short deck without assisted launch", "provides local combat air patrol", "accepts one air, surface, land, or protection mission pack"], warfare: ["reconnaissance"], missionReach: "310 invented nautical miles", trackCapacity: 6, trackingMethods: ["active radar", "infrared", "cooperative network"] },
  { id: "short-deck-strike-aircraft", name: "Low-signature short-deck strike aircraft", short: "LOW-SIGNATURE DECK STRIKE", role: "Coastal penetration · surface or land effect", points: 1.35, aircrew: 1, supportCrew: 10, kind: "short-deck", armamentSlots: 1, armamentIds: ["airborne-anti-surface-pack", "airborne-land-effect-pack", "airborne-emitter-homing-pack", "airborne-decoy-pack"], capabilities: ["reduces visual and electronic cues during ingress", "operates from a short-deck aviation ship", "accepts one surface, land, emitter-homing, or protection pack"], warfare: ["reconnaissance"], missionReach: "320 invented nautical miles", trackCapacity: 4, trackingMethods: ["passive emitter", "electro-optical", "scene correlation"], visualSignature: "low" },
  { id: "electromagnetic-support-aircraft", name: "Electromagnetic-support aircraft", short: "ELECTROMAGNETIC SUPPORT", role: "Emitter location · protection · disruption", points: 1.4, aircrew: 2, supportCrew: 9, kind: "catapult", armamentSlots: 1, armamentIds: ["airborne-electromagnetic-pack", "airborne-emitter-homing-pack", "airborne-decoy-pack"], capabilities: ["maps emitter activity", "supports stand-off disruption and deception", "requires an assisted-launch aviation ship"], warfare: ["electromagnetic-operations", "reconnaissance"], missionReach: "510 invented nautical miles", trackCapacity: 24, trackingMethods: ["passive emitter", "cooperative network"] },
  { id: "fixed-wing-surveillance-aircraft", name: "Fixed-wing surveillance aircraft", short: "FIXED-WING SURVEILLANCE", role: "Wide-area air picture · task-group coordination", points: 1.35, aircrew: 4, supportCrew: 12, kind: "catapult", armamentSlots: 1, armamentIds: ["airborne-relay-pack", "airborne-decoy-pack"], capabilities: ["extends air and surface detection beyond the ship horizon", "coordinates intercept geometry", "requires an assisted-launch aviation ship"], warfare: ["air-defense", "reconnaissance"], missionReach: "590 invented nautical miles", trackCapacity: 40, trackingMethods: ["active radar", "passive emitter", "cooperative network"] },
  { id: "maritime-patrol-aircraft", name: "Deck-launched maritime patrol aircraft", short: "MARITIME PATROL AIRCRAFT", role: "Broad-area acoustic search · surface classification", points: 1.3, aircrew: 4, supportCrew: 10, kind: "catapult", armamentSlots: 2, armamentIds: ["airborne-acoustic-pack", "airborne-anti-surface-pack", "airborne-decoy-pack"], capabilities: ["searches a broad undersea patrol box", "maintains surface track custody", "carries up to two compatible acoustic, surface, or protection packs"], warfare: ["undersea-operations", "surface-operations", "reconnaissance"], missionReach: "650 invented nautical miles", trackCapacity: 20, trackingMethods: ["active acoustic", "passive acoustic", "active radar", "electro-optical"] },
  { id: "command-relay-aircraft", name: "Airborne command-relay aircraft", short: "COMMAND RELAY AIRCRAFT", role: "Track fusion · distributed command exchange", points: 1.15, aircrew: 3, supportCrew: 10, kind: "catapult", armamentSlots: 1, armamentIds: ["airborne-relay-pack", "airborne-electromagnetic-pack", "airborne-decoy-pack"], capabilities: ["fuses reports from dispersed maritime sensors", "extends command exchange beyond the surface horizon", "adds no offensive effect without a compatible pack"], warfare: ["electromagnetic-operations", "reconnaissance"], missionReach: "580 invented nautical miles", trackCapacity: 40, trackingMethods: ["passive emitter", "cooperative network"] },
  { id: "rotary-surveillance-aircraft", name: "Rotary-wing surveillance aircraft", short: "ROTARY SURVEILLANCE", role: "Compact-deck warning · surface tracking", points: 1.15, aircrew: 4, supportCrew: 9, kind: "rotary", armamentSlots: 1, armamentIds: ["airborne-relay-pack", "airborne-decoy-pack"], capabilities: ["provides over-horizon warning from compact decks", "tracks surface movement around terrain", "lands on any rotary-capable selected vessel with space"], warfare: ["air-defense", "surface-operations", "reconnaissance"], missionReach: "230 invented nautical miles", trackCapacity: 22, trackingMethods: ["active radar", "electro-optical", "cooperative network"] },
  { id: "maritime-mission-helicopter", name: "Maritime mission helicopter", short: "MARITIME HELICOPTER", role: "Acoustic search · surface identification", points: 1, aircrew: 3, supportCrew: 7, kind: "rotary", armamentSlots: 1, armamentIds: ["airborne-acoustic-pack", "airborne-anti-surface-pack", "airborne-rescue-support-pack", "maritime-safeguarding-pack", "airborne-decoy-pack"], capabilities: ["deploys acoustic sensors and localizes undersea contacts", "identifies surface contacts beyond the screen", "supports rescue, documentation, and protected handoff with the safeguarding pack"], warfare: ["undersea-operations", "surface-operations", "reconnaissance", "maritime-interdiction"], missionReach: "175 invented nautical miles", trackCapacity: 12, trackingMethods: ["active acoustic", "passive acoustic", "electro-optical"] },
  { id: "mine-countermeasure-rotorcraft", name: "Mine-countermeasure rotorcraft", short: "MINE-SEARCH ROTORCRAFT", role: "Lane survey · anomaly classification · marking", points: 0.9, aircrew: 3, supportCrew: 8, kind: "rotary", armamentSlots: 1, armamentIds: ["airborne-mine-sensing-pack", "airborne-decoy-pack"], capabilities: ["surveys a bounded suspected mine lane", "classifies anomalies with multiple sensor methods", "marks contacts for a selected neutralization host"], warfare: ["mine-countermeasures", "reconnaissance"], missionReach: "140 invented nautical miles", trackCapacity: 12, trackingMethods: ["magnetic anomaly", "bathymetric comparison", "electro-optical"] },
  { id: "shipborne-rescue-rotorcraft", name: "Shipborne rescue rotorcraft", short: "RESCUE ROTORCRAFT", role: "Personnel recovery · scene coordination", points: 0.7, aircrew: 3, supportCrew: 6, kind: "rotary", armamentSlots: 1, armamentIds: ["airborne-rescue-support-pack", "maritime-safeguarding-pack", "airborne-decoy-pack"], capabilities: ["locates a distress beacon and maps the recovery scene", "recovers personnel or transfers casualties", "supports protected evidence and survivor handoff"], warfare: ["surface-operations", "reconnaissance", "maritime-interdiction"], missionReach: "180 invented nautical miles", trackCapacity: 8, trackingMethods: ["distress beacon", "electro-optical", "infrared"] },
  { id: "heavy-utility-rotorcraft", name: "Heavy utility rotorcraft", short: "HEAVY UTILITY ROTORCRAFT", role: "Lift · recovery · relief", points: 0.85, aircrew: 3, supportCrew: 7, kind: "rotary", armamentSlots: 1, armamentIds: ["airborne-rescue-support-pack", "airborne-decoy-pack"], capabilities: ["moves priority teams and stores", "supports rescue and casualty evacuation", "lands on any rotary-capable selected vessel with space"], warfare: ["reconnaissance"], missionReach: "160 invented nautical miles", trackCapacity: 6, trackingMethods: ["distress beacon", "electro-optical", "infrared"] },
  { id: "uncrewed-combat-aircraft", name: "Shipborne uncrewed combat aircraft", short: "UNCREWED COMBAT AIRCRAFT", role: "Persistent scout · configurable combat effect", points: 0.75, aircrew: 0, supportCrew: 4, kind: "uncrewed-fixed-wing", armamentSlots: 1, armamentIds: ["air-to-air-mission-pack", "airborne-anti-surface-pack", "airborne-land-effect-pack", "airborne-electromagnetic-pack", "airborne-decoy-pack"], capabilities: ["extends sensing without crewed exposure", "accepts one air, surface, land, electromagnetic, or protection pack", "lands only on a selected vessel with fixed-wing uncrewed space"], warfare: ["reconnaissance"], missionReach: "520 invented nautical miles", trackCapacity: 12, trackingMethods: ["active radar", "passive emitter", "cooperative network"] },
  { id: "long-endurance-uncrewed-strike", name: "Long-endurance uncrewed strike aircraft", short: "LONG-ENDURANCE UNCREWED STRIKE", role: "Persistent stand-off watch · delayed strike", points: 0.95, aircrew: 0, supportCrew: 5, kind: "uncrewed-fixed-wing", armamentSlots: 2, armamentIds: ["airborne-anti-surface-pack", "airborne-land-effect-pack", "airborne-emitter-homing-pack", "airborne-decoy-pack"], capabilities: ["holds a distant patrol while awaiting positive identification", "accepts two compatible strike or protection packs", "requires a selected fixed-wing uncrewed aviation host"], warfare: ["reconnaissance"], missionReach: "760 invented nautical miles", trackCapacity: 8, trackingMethods: ["passive emitter", "electro-optical", "cooperative network"] },
  { id: "low-signature-uncrewed-scout", name: "Low-signature uncrewed reconnaissance aircraft", short: "LOW-SIGNATURE UNCREWED SCOUT", role: "Covert reconnaissance · emitter mapping · limited effect", points: 0.7, aircrew: 0, supportCrew: 4, kind: "uncrewed-fixed-wing", armamentSlots: 1, armamentIds: ["airborne-anti-surface-pack", "airborne-land-effect-pack", "airborne-emitter-homing-pack", "airborne-electromagnetic-pack", "airborne-relay-pack", "airborne-decoy-pack"], capabilities: ["uses reduced visual and electronic cues", "maps emitters and passes cooperative tracks", "accepts one reconnaissance, protection, or limited-effect pack"], warfare: ["electromagnetic-operations", "reconnaissance"], missionReach: "720 invented nautical miles", trackCapacity: 24, trackingMethods: ["passive emitter", "electro-optical", "cooperative network"], visualSignature: "low" },
  { id: "uncrewed-refueling-aircraft", name: "Uncrewed airborne refuelling aircraft", short: "UNCREWED AIR REFUELLING", role: "Sortie extension · recovery margin", points: 0.55, aircrew: 0, supportCrew: 4, kind: "uncrewed-fixed-wing", armamentSlots: 0, armamentIds: [], capabilities: ["extends the on-station time of compatible fixed-wing aircraft", "creates recovery margin without crewed exposure", "adds no independent combat effect"], warfare: ["reconnaissance"], missionReach: "600 invented nautical miles", trackCapacity: 4, trackingMethods: ["cooperative network", "electro-optical"] },
  { id: "uncrewed-surveillance-rotorcraft", name: "Uncrewed surveillance rotorcraft", short: "UNCREWED VERTICAL SURVEILLANCE", role: "Persistent local sensing · acoustic cueing", points: 0.45, aircrew: 0, supportCrew: 3, kind: "uncrewed-vertical", armamentSlots: 1, armamentIds: ["airborne-acoustic-pack", "airborne-mine-sensing-pack", "airborne-decoy-pack"], capabilities: ["maintains a local surface and undersea watch", "cues crewed search assets", "accepts one acoustic, mine-sensing, or protection pack"], warfare: ["undersea-operations", "surface-operations", "reconnaissance"], missionReach: "125 invented nautical miles", trackCapacity: 14, trackingMethods: ["passive acoustic", "electro-optical", "cooperative network"] },
  { id: "uncrewed-logistics-aircraft", name: "Uncrewed vertical logistics aircraft", short: "UNCREWED LOGISTICS", role: "Priority stores · distributed resupply", points: 0.35, aircrew: 0, supportCrew: 2, kind: "uncrewed-vertical", armamentSlots: 1, armamentIds: ["airborne-decoy-pack"], capabilities: ["moves compact priority stores between compatible decks", "reduces crewed exposure during resupply", "provides no combat coverage without a compatible protection pack"], warfare: ["reconnaissance"], missionReach: "95 invented nautical miles", trackCapacity: 4, trackingMethods: ["cooperative network", "electro-optical"] },
];
